name: CLA Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  verify-cla:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      statuses: write
      contents: read
    steps:
      - name: Check PR body for CLA agreement checkbox
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = pr && pr.body ? pr.body : '';
            const agreed = /\- \[(x|X)\] I have read and agree to the Contributor License Agreement/i.test(body);
            if (!agreed) {
              core.setFailed('CLA not agreed. Please check the CLA box in the PR template.');
            } else {
              core.notice('CLA checkbox detected.');
            }
